name = "Time-Rift-Universe"
author = "PoiBoy34"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "059dc6a49f2c5b75a01b9f6dd9aa6eb7db7d318b84db8afde16ca2469131698d"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
